openapi: 3.1.1
info:
  title: Fingerprint server API
  version: '0.1'
paths:
  /elements/{element_id}:
    get:
      responses:
        '200':
          description: get endpoint
          content:
            application/json:
              schema:
                $ref: './components/Union.yaml'
