openapi: 3.1.1
info:
  title: test
  version: '1.0'
paths:
  /v4/events:
    get:
      operationId: getEvents
      parameters:
        - name: bot
          in: query
          schema:
            $ref: '#/components/schemas/BotEnum'
          description: Bot filter description.
        - name: visitor_id
          in: query
          schema:
            type: string
        - name: device
          in: query
          schema:
            $ref: '#/components/schemas/GetEventsDeviceEnum'
  /v4/users:
    get:
      operationId: getUsers
      parameters:
        - name: bot
          in: query
          schema:
            $ref: '#/components/schemas/BotEnum'
          description: Bot filter description.
  /v4/visits:
    get:
      operationId: getVisits
      parameters:
        - name: bot
          in: query
          schema:
            $ref: '#/components/schemas/GetVisitsBotEnum'
          description: Different description.
components:
  schemas:
    DeviceEnum:
      type: object
      properties:
        platform:
          $ref: '#/components/schemas/PlatformEnum'
    BotEnum:
      type: string
      enum:
        - all
        - good
      description: Bot filter description.
    GetEventsDeviceEnum:
      type: string
      enum:
        - desktop
        - mobile
    GetVisitsBotEnum:
      type: string
      enum:
        - detected
        - not_detected
      description: Different description.
    PlatformEnum:
      type: string
      enum:
        - web
        - mobile
