openapi: 3.1.1
info:
  title: test
  version: '1.0'
paths:
  /v4/events:
    get:
      operationId: getEvents
      parameters:
        - name: bot
          in: query
          schema:
            type: string
            enum:
              - all
              - good
          description: Bot filter description.
        - name: visitor_id
          in: query
          schema:
            type: string
  /v4/users:
    get:
      operationId: getUsers
      parameters:
        - name: bot
          in: query
          schema:
            type: string
            enum:
              - detected
              - not_detected
components:
  schemas:
    Device:
      type: object
      properties:
        platform:
          type: string
          enum:
            - web
            - mobile
