openapi: 3.1.1
components:
  schemas:
    Kind:
      type: string
      enum:
        - allow
        - block
    ActionAllow:
      description: allow action
      allOf:
        - properties:
            shared:
              type: string
          required:
            - shared
        - type: object
          properties:
            type:
              allOf:
                - $ref: '#/components/schemas/Kind'
                - const: allow
            allow_only:
              type: string
          required:
            - type
    ActionBlock:
      description: block action
      allOf:
        - properties:
            shared:
              type: string
          required:
            - shared
        - type: object
          properties:
            type:
              allOf:
                - $ref: '#/components/schemas/Kind'
                - const: block
            block_only:
              type: string
          required:
            - type
    Action:
      type: object
      description: action union
      oneOf:
        - $ref: '#/components/schemas/ActionAllow'
        - $ref: '#/components/schemas/ActionBlock'
      discriminator:
        propertyName: type
