openapi: 3.1.1
info:
  title: test
  version: '1.0'
paths:
  /v4/events:
    get:
      operationId: getEvents
      parameters:
        - name: timestamp
          in: query
          required: false
          description: The updated description
          schema:
            type: integer
            format: int64
          x-parameter-alias: timestamp_alias
        - name: timestamp_alias
          in: query
          required: false
          description: The description for the alias
          schema:
            type: string
            format: date-time
          x-aliased-parameter-name: timestamp
