events:
  path: /events/{event_id}
  methods:
    - get
    - patch
events-search:
  path: /events
  methods:
    - get
visitors:
  path: /visitors/{visitor_id}
  methods:
    - delete
webhook:
  path: /webhook
  methods:
    - post
related-visitors:
  path: /related-visitors
  methods:
    - get
