events:
  path: /events/{request_id}
  methods:
    - get
    - put
search:
  path: /events/search
  methods:
    - get
visitors:
  path: /visitors/{visitor_id}
  methods:
    - get
    - delete
webhook:
  path: /webhook
  methods:
    - trace
related-visitors:
  path: /related-visitors
  methods:
    - get
events-search:
  path: /events/search
  methods:
    - get
