type: object
additionalProperties: false
required:
  - result
properties:
  result:
    type: boolean
    description: >
      `true` if the request is from a privacy aware browser (e.g. Tor) or from a browser in which fingerprinting is blocked. Otherwise `false`.
