type: object
additionalProperties: false
properties:
  code:
    type: string
    description: |
      Error code:
       * `TooManyRequests` - the limit on secret API key requests per second has been exceeded
       * `Failed` - internal server error
    enum:
      - TooManyRequests
      - Failed
    example: TooManyRequests
  message:
    type: string
    example: too many requests
required:
  - code
  - message
