openapi: 3.0.3
info:
  title: Fingerprint Server API
  description: |
    Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
    Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
  version: '3'
  contact:
    name: Fingerprint Support
    email: support@fingerprint.com
tags:
  - name: Events
    description: |
      Retrieve or update information about individual events using the event's `requestId`.
  - name: Event Search
    description: |
      Search for events matching one or more filters.
  - name: Visitors
    description: |
      Retrieve all events of an individual visitor using their `visitorId`.
servers:
  - url: https://api.fpjs.io
    description: Global
  - url: https://eu.api.fpjs.io
    description: EU
  - url: https://ap.api.fpjs.io
    description: Asia (Mumbai)
security:
  - ApiKeyHeader: []
  - ApiKeyQuery: []
x-readme:
  samples-languages:
    - curl
    - node
    - php
    - python
    - csharp
    - java
    - go
paths:
  /events/{request_id}:
    $ref: 'paths/events.yaml'
  /events/search:
    $ref: 'paths/event-search.yaml'
  /visitors/{visitor_id}:
    $ref: 'paths/visitors.yaml'
components:
  securitySchemes:
    ApiKeyHeader:
      type: apiKey
      in: header # can be "header", "query" or "cookie"
      name: Auth-API-Key # name of the header, query parameter or cookie
    ApiKeyQuery:
      type: apiKey
      in: query # can be "header", "query" or "cookie"
      name: api_key # name of the header, query parameter or cookie
