openapi: 3.0.3
info:
  title: Fingerprint Pro Server API
  description: |
    Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
    Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
  version: '3'
  contact:
    name: Fingerprint Support
    email: support@fingerprint.com
tags:
  - name: Events
    description: |
      Using the Server API you can retrieve information about individual analysis events using the event's `requestId`.
  - name: Visitors
    description: |
      Using the Server API you can retrieve visitor history of individual visitors using their `visitorId`.
servers:
  - url: https://api.fpjs.io
    description: Global
  - url: https://eu.api.fpjs.io
    description: EU
  - url: https://ap.api.fpjs.io
    description: Asia (Mumbai)
security:
  - ApiKeyHeader: []
  - ApiKeyQuery: []
x-readme:
  samples-languages:
    - curl
    - node
    - php
    - python
    - csharp
    - java
    - go
paths:
  /events/{request_id}:
    $ref: 'paths/events.yaml'
  /visitors/{visitor_id}:
    $ref: 'paths/visitors.yaml'
  /webhook:
    trace:
      tags:
        - Fingerprint
      description: Fake path to describe webhook format. More information about webhooks can be found in the [documentation](https://dev.fingerprint.com/docs/webhooks)
      responses:
        default:
          description: Dummy for the schema
      callbacks:
        webhook:
          webhook:
            post:
              description: You can use HTTP basic authentication and set up credentials in your [Fingerprint account](https://dashboard.fingerprint.com/login)
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: 'components/schemas/WebhookVisit.yaml'
                    example:
                      externalValue: '/examples/webhook.json'
              responses:
                default:
                  description: The server doesn't validate the answer.
components:
  securitySchemes:
    ApiKeyHeader:
      type: apiKey
      in: header # can be "header", "query" or "cookie"
      name: Auth-API-Key # name of the header, query parameter or cookie
    ApiKeyQuery:
      type: apiKey
      in: query # can be "header", "query" or "cookie"
      name: api_key # name of the header, query parameter or cookie
