openapi: 3.1.1
info:
  title: Fingerprint Server API
  description: |
    Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
    Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
  version: '3'
  contact:
    name: Fingerprint Support
    email: support@fingerprint.com
  license:
    name: MIT
    url: https://github.com/fingerprintjs/fingerprint-pro-server-api-openapi/blob/main/LICENSE
tags:
  - name: Events
    description: |
      Retrieve or update information about individual events using the event's request ID.
  - name: Event Search
    description: |
      Search for events matching one or more filters.
  - name: Visitors
    description: |
      Retrieve all events of an individual visitor using their visitor ID.
  - name: Related Visitors
    description: |
      Find visitor IDs that originated from a different browser on the same mobile device.
servers:
  - url: https://api.fpjs.io
    description: Global
  - url: https://eu.api.fpjs.io
    description: EU
  - url: https://ap.api.fpjs.io
    description: Asia (Mumbai)
security:
  - ApiKeyHeader: []
  - ApiKeyQuery: []
paths:
  /events/{request_id}:
    $ref: 'paths/events.yaml'
  /events/search:
    $ref: 'paths/event-search.yaml'
  /visitors/{visitor_id}:
    $ref: 'paths/visitors.yaml'
  /related-visitors:
    $ref: './paths/related-visitors.yaml'
webhooks:
  event:
    post:
      operationId: postWebhookEvent
      summary: If configured, a webhook event will be posted to the provided endpoint. More information about webhooks can be found in the [documentation](https://dev.fingerprint.com/docs/webhooks)
      requestBody:
        description: Identification details and smart signals of the event.
        content:
          application/json:
            schema:
              $ref: 'components/schemas/Webhook.yaml'
      responses:
        "200":
          description: Return a 200 status to indicate that the data was received successfully
components:
  securitySchemes:
    ApiKeyHeader:
      type: apiKey
      in: header # can be "header", "query" or "cookie"
      name: Auth-API-Key # name of the header, query parameter or cookie
    ApiKeyQuery:
      type: apiKey
      in: query # can be "header", "query" or "cookie"
      name: api_key # name of the header, query parameter or cookie
