openapi: 3.0.3
info:
  title: Related Visitors API
  description: |
    Use this API to unify and personalize the experience for your anonymous users who visit your website from regular and in-app browsers.
  version: '1.0'
  contact:
    name: Fingerprint Support
    email: support@fingerprint.com
tags:
  - name: Related Visitors
    description: |
      Find visitor IDs that originated from a different browser on the same mobile device.
servers:
  - url: https://api.fpjs.io
    description: Recommended if your customer base is primarily in the Americas.
  - url: https://eu.api.fpjs.io
    description: Recommended if your customer base is primarily in Europe.
  - url: https://ap.api.fpjs.io
    description: Recommended if your customer base is primarily in the APAC region.
security:
  - ApiKeyHeader: []
  - ApiKeyQuery: []
paths:
  /related-visitors:
    $ref: './paths/related-visitors.yaml'
components:
  securitySchemes:
    ApiKeyHeader:
      type: apiKey
      in: header # can be "header", "query" or "cookie"
      name: Auth-API-Key # name of the header, query parameter or cookie
    ApiKeyQuery:
      type: apiKey
      in: query # can be "header", "query" or "cookie"
      name: api_key # name of the header, query parameter or cookie
