name: Lint changesets
on:
  pull_request:
    paths:
      - '.changeset/**'
      - 'scripts/lintChangesets.ts'
      - '.github/workflows/lint-changesets.yml'

jobs:
  lint-changesets:
    name: Lint changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install PNPM
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: Set Node.js 22.x
        uses: actions/setup-node@v7
        with:
          node-version: 22.x
          cache: pnpm
      - name: Install Node packages
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Lint changesets
        run: pnpm lint:changesets
