name: Publish schema to GH pages and Readme

on:
  push:
    branches:
      - main

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - uses: ./.github/actions/test-and-build
        with:
          testSubscriptions: '${{ secrets.TEST_SUBSCRIPTIONS }}'
      - name: Upload GitHub pages artifact 📦
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist
      - name: Upload built schemas for Readme 📦
        uses: actions/upload-artifact@v7
        with:
          name: schemas
          path: dist/schemas
          if-no-files-found: error
          retention-days: 1

  deploy-pages:
    name: Deploy to GitHub pages 🚀📘
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v5

  deploy-readme:
    name: Deploy to Readme 🚀🦉
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download built schemas
        uses: actions/download-artifact@v8
        with:
          name: schemas
          path: dist/schemas
      - name: Deploy to Readme APIv3 Reference 🚀🦉
        uses: readmeio/rdme@6c330ae4130595720421809c4eaa37ba95d07f87 # v10.9.5
        with:
          rdme: openapi upload dist/schemas/fingerprint-server-api-readme-explorer.yaml --key=${{ secrets.README_API_KEY }} --slug=fingerprint-pro-server-api.json
      - name: Deploy to Readme APIv4 Reference 🚀🦉
        uses: readmeio/rdme@6c330ae4130595720421809c4eaa37ba95d07f87 # v10.9.5
        with:
          rdme: openapi upload dist/schemas/fingerprint-server-api-v4-with-examples.yaml --key=${{ secrets.README_API_KEY }} --slug=fingerprint-server-api-readme-explorer.yaml
