name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: 'Release project'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-sdk-changesets.yml@v1
    with:
      version-command: pnpm changeset-version
      publish-command: pnpm exec changeset publish
      language: node
      language-version: '21'
      prepare-command: |
        pnpm build
    secrets:
      GH_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
