name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: 'Release project'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-sdk-changesets.yml@v1
    with:
      appId: ${{ vars.APP_ID }}
      version-command: pnpm changeset-version
      publish-command: pnpm exec changeset publish
      language: node
      language-version: '21'
      prepare-command: |
        pnpm build
    secrets:
      # We can't use default token, because it will result on not triggering the "upload-changesets.yml" workflow on release
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
