name: Release
on:
  push:
    branches:
      - main

jobs:
  get-token:
    name: Get token
    environment: production
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.app-token.outputs.token }}
    steps:
      - name: 'Get token for the GitHub App'
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
  release:
    needs: [get-token]
    name: 'Release project'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-sdk-changesets.yml@v1
    with:
      version-command: pnpm changeset-version
      publish-command: pnpm exec changeset publish
      language: node
      language-version: '21'
      prepare-command: |
        pnpm build
    secrets:
      # We can't use default token, because it will result on not triggering the "upload-changesets.yml" workflow on release
      GH_RELEASE_TOKEN: ${{ needs.get-token.outputs.token }}
