on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string
      pre-release:
        description: 'Whether to create a pre-release first for the SDKs'
        required: false
        default: false
name: Sync Server-Side SDKs schema
jobs:
  sync-node:
    name: 'Sync schema in Node SDK'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/update-server-side-sdk-schema.yml@v1
    with:
      tag: ${{ inputs.tag }}
      language: node
      language-version: 21
      generate-command: 'pnpm generateTypes'
      schema-path: resources/fingerprint-server-api.yaml
      examples-path: tests/mocked-responses-tests/mocked-responses-data
      app-id: ${{ vars.APP_ID }}
      repository: fingerprintjs-pro-server-api-node-sdk
      pre-release: ${{ inputs.pre-release }}
      ignored-scopes: visitors-api
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
