# TODO Remove this workflow before merge
on:
  release:
    types:
      - released
      - published
name: Sync Server-Side SDKs schema on release
jobs:
  sync-node:
    name: 'Sync schema in Node SDK'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/update-server-side-sdk-schema.yml@v1
    with:
      tag: ${{ github.event.release.tag_name }}
      language: node
      language-version: 21
      generate-command: 'pnpm generateTypes'
      schema-path: resources/fingerprint-server-api.yaml
      examples-path: tests/mocked-responses-tests/mocked-responses-data
      app-id: ${{ vars.APP_ID }}
      repository: fingerprintjs-pro-server-api-node-sdk
      ignored-scopes: visitors-api
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
