# Reference on this file: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Lint, build and test
on:
  workflow_call:
  pull_request_target:
jobs:
  build:
    name: Lint, build and test
    runs-on: ubuntu-latest
    environment: test
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/test-and-build
        with:
          testSubscriptions: '${{ secrets.TEST_SUBSCRIPTIONS }}'
