name: Upload schemas
on:
  release:
    types:
      - published

jobs:
  upload-schemas:
    name: Upload schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: 'Build schemas'
        run: pnpm build

      - name: 'Zip examples'
        run: zip -r examples.zip examples
        working-directory: dist

      - name: Upload schemas to a GitHub release
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'dist/schemas/*.yaml'
          file_glob: true
          tag: ${{ github.event.release.tag_name }}

      - name: Upload examples to a GitHub release
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/examples.zip
          tag: ${{ github.event.release.tag_name }}

      - name: Upload scopes to a GitHub release
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'config/scopes.yaml'
          tag: ${{ github.event.release.tag_name }}


