name: Upload schemas
on:
  release:
    types:
      - published

jobs:
  upload-schemas:
    name: Upload schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install PNPM
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          run_install: true

      - name: 'Build schemas'
        run: pnpm build

      - name: 'Zip examples'
        run: zip -r examples.zip examples
        working-directory: dist

      - name: Upload schemas to a GitHub release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'dist/schemas/*.yaml'
          file_glob: true
          tag: ${{ github.event.release.tag_name }}

      - name: Upload examples to a GitHub release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/examples.zip
          tag: ${{ github.event.release.tag_name }}

      - name: Upload scopes to a GitHub release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'config/scopes.yaml'
          tag: ${{ github.event.release.tag_name }}


