# Reference on this file: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Validate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
jobs:
  set_datadog_team:
    name: 'Set Datadog team'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/set-datadog-team.yml@v1
    secrets:
      DD_API_KEY: ${{ secrets.INTEGRATIONS_DATADOG_API_KEY }}

  validate:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/test-and-build
        with:
          testSubscriptions: '${{ secrets.TEST_SUBSCRIPTIONS }}'
